print("S='Code'");
print("len(S)");
print("S[0], S[1], S[2], S[3], S[4]");
print("S[-1], S[-2], S[-3], S[-4], S[-5]");
print("S[1:4]");
print("S[:3], S[3:]");
print("S[::2], S[1::2]");       
print("S[::-1]");
print("S[len(S)-1");
print("S[-1]");
print("s[1:]");
print("S");
print("S[0:3]");
print("S[:3]");
print("S[:-1]");
print("S[:]");
print("S");
print("S+'xyz'");
print("S");
print("S*3");
