print("S='Code'");
print("S.find('o')");
print("S");
print("S.replace('od','abl')");
print("S");
print("Line='aaa,bbb,ccc,dd,ee'");
print("Line.split(',')");
print("Line");
print("S='  Code   '");
print("S.upper()");
print("S.isalpha()");
print("Line='aaa,bbb,ccc,dd,ee\n'");
print("Line.strip()");
print("Line.rstrip().strip()");
print("tool='Python'");
print("major=3");
print("minor=3");
print("Using %s version %d.%d" % (tool, major, minor+9));
print("Using {} version {}.{}".format(tool, major, minor+9));
print(f"Using {tool} version {major}.{minor+9}");
print("'%.2f |%+05d' % (3.14159, -42)");
print("'{1:,.2f} | {0}'.format('sapp'[1:], 296999.256)");
print("f'{296999.256:,.2f} | {'sapp'[1:]}' ");
