x=set('abcde')
y={'a','b','c','d','e',1.23}
print(x)
print(y)
z=set()
z
print(z)
z=set([1.2,'a',3,1.2,'a'])
print(z)
print(1,*'abc',*[1,2,3],*{1,2,3})
x=set('abcd')
y=set('cdef')
print(x)
print(y)
print(x|y)
print(x&y)
print(x-y)
print(y-x)
print(x^y)
print(x<y,x>y)
print('d' in x)
print('d' in y)
print('d' in x and 'd' in y)
print('d' in'code',2 in[1,2,3],3 in{1,2,3})
z=x.intersection(y)
print(z)
z.add('HACK')
print(z)
z.update(set(['X','Y','Z']))
print(z)
z.remove('Y')
print(z)
for item in set('abc'):
    print(item * 3)
print({'a', 'b', 'c'} | {'d', 'e', 'f'})

S = set([1, 2, 3])
print(S | set([3, 4]))  
print(S | set([3, 4]))  
